# NumPy 

-For scientific computing with Python. <br>
-We use it when we work on numerical data. <br>
-Powerful tool of numpy is Arrays.

In [1]:
import numpy as np        

In [2]:
arr = [1,2,3,4,5,6,7]
arr

[1, 2, 3, 4, 5, 6, 7]

In [3]:
np.array(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
arr = [[10,11,12],[20,21,22],[30,31,32]]
arr

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [5]:
np.array(arr)

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [10]:
np.arange(0,10) # values from 0 to 9. 



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5,100,10)       # Specify start, stop and step values as input

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [13]:
np.zeros(10)        

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((10,15))        

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
x = np.ones(10) 
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((10,15))         

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,30,10)   # means there must be 10 values between 0 to 30 

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [32]:
np.eye(5) # diagonal ones

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random 


In [33]:
np.random.rand(4)

array([0.39914751, 0.87044955, 0.42079721, 0.04585379])

In [34]:
np.random.rand(3,2)

array([[0.52250293, 0.17887537],
       [0.26161889, 0.56771511],
       [0.38391917, 0.30227128]])

In [35]:
np.random.randn(5) # randn is to take values from normal distribution. hence values could range from -1 to 1 range...

array([-0.32043331, -0.44775067,  1.20049124, -0.2716445 ,  0.32724172])

In [36]:
np.random.randn(3,2)

array([[-0.31502019, -1.17065585],
       [-0.42739916,  1.83518158],
       [-1.18093537,  1.1659966 ]])

In [40]:
np.random.randint(10,1000)  # randint for integers.

81

In [41]:
np.random.randint(500,1000,6)  # 6 random integers from 500 to 1000

array([698, 560, 970, 721, 868, 993])

### arrays...

In [42]:
rarr = np.random.randint(0,1000,10)

In [57]:
rarr

array([695, 694, 809, 394, 872, 895,   9, 663, 344, 400])

In [80]:
rarr.dtype

dtype('int32')

In [69]:
rarr.shape

(10,)

In [70]:
rarr.reshape(5,2) # can't reshape into any other dimension... 

array([[695, 694],
       [809, 394],
       [872, 895],
       [  9, 663],
       [344, 400]])

In [75]:
rarr.reshape(5,2).shape

(5, 2)

In [76]:
rarr.max() # returns max value 

895

In [77]:
rarr.min()

9

In [78]:
rarr.argmax() # returns index of max() value 

5

In [79]:
rarr.argmin() # index of min value

6

In [84]:
x = rarr.reshape(5,2)
x

array([[695, 694],
       [809, 394],
       [872, 895],
       [  9, 663],
       [344, 400]])

In [86]:
x.T # T WOULD TRANSPOSE THE MATRIX. 

array([[695, 809, 872,   9, 344],
       [694, 394, 895, 663, 400]])

In [87]:
rarr[8]

344

In [96]:
m = rarr[0:5]
m

array([695, 100, 100, 100, 872])

In [97]:
rarr[[0,6,7, 2]] # IT WOULD PRINT 4 VALUES PRESENT IN THE INDEXES. 

array([695,   9, 663, 100])

In [98]:
# called broadcasting
rarr[1:4]=100
rarr

array([695, 100, 100, 100, 872, 895,   9, 663, 344, 400])

In [101]:
x = rarr
x[:]=99 # changing all values 
x

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [102]:
copy_array = x.copy()

copy_array

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [103]:
marr = np.array(([1,11,111],[2,22,222],[3,33,333]))
marr

array([[  1,  11, 111],
       [  2,  22, 222],
       [  3,  33, 333]])

In [105]:
marr[1]

array([  2,  22, 222])

In [108]:
marr[2][1] # OR CAN ALSO BE WRITTEN AS: marr[2,1]

33

In [109]:
# Slicing matrix
marr[:2,1:]

array([[ 11, 111],
       [ 22, 222]])

In [111]:
marr[2,:]

array([  3,  33, 333])

In [113]:
marr = np.random.randint(1,100,20)
marr = marr.reshape(5,4)
marr

array([[74, 54, 81, 70],
       [78, 14, 86, 19],
       [69, 56, 87, 32],
       [39, 94, 68, 19],
       [76,  7, 13, 31]])

In [114]:
marr[:,(1,3)]

array([[54, 70],
       [14, 19],
       [56, 32],
       [94, 19],
       [ 7, 31]])

In [117]:
marr[:,(2,3)]

array([[81, 70],
       [86, 19],
       [87, 32],
       [68, 19],
       [13, 31]])

In [118]:
marr <10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [119]:
marr[marr>15]

array([74, 54, 81, 70, 78, 86, 19, 69, 56, 87, 32, 39, 94, 68, 19, 76, 31])

### Operations

In [123]:
marr+marr # adds ...SIMILARLY SUBTRACT OR DIVIDE...

array([[148, 108, 162, 140],
       [156,  28, 172,  38],
       [138, 112, 174,  64],
       [ 78, 188, 136,  38],
       [152,  14,  26,  62]])

In [124]:
marr * marr

array([[5476, 2916, 6561, 4900],
       [6084,  196, 7396,  361],
       [4761, 3136, 7569, 1024],
       [1521, 8836, 4624,  361],
       [5776,   49,  169,  961]])

In [126]:
marr/marr # get a warning for 0......

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [127]:
100/marr

array([[ 1.35135135,  1.85185185,  1.2345679 ,  1.42857143],
       [ 1.28205128,  7.14285714,  1.1627907 ,  5.26315789],
       [ 1.44927536,  1.78571429,  1.14942529,  3.125     ],
       [ 2.56410256,  1.06382979,  1.47058824,  5.26315789],
       [ 1.31578947, 14.28571429,  7.69230769,  3.22580645]])

In [136]:
np.sqrt(marr)

# similarly: 

array([[8.60232527, 7.34846923, 9.        , 8.36660027],
       [8.83176087, 3.74165739, 9.2736185 , 4.35889894],
       [8.30662386, 7.48331477, 9.32737905, 5.65685425],
       [6.244998  , 9.69535971, 8.24621125, 4.35889894],
       [8.71779789, 2.64575131, 3.60555128, 5.56776436]])

In [146]:
'''
#for e^x = .exp(marr)
#for sin() = .sin(marr)
log, cos, square, std # standard deviation, var, mean...
'''

'\n#for e^x = .exp(marr)\n#for sin() = .sin(marr)\nlog, cos, square, std # standard deviation, var, mean...\n'

In [147]:
np.max(marr) # similarly min(), argmax()....

1.5515023020907657

In [148]:

marr = np.random.randn(5,4)
np.round(marr,decimals=2)     #rounding off the values to 2 decimal places

array([[-0.93,  0.91,  0.85, -0.29],
       [-1.79, -0.14, -0.32,  1.79],
       [-0.95,  0.01, -0.15,  1.08],
       [-0.46,  1.83, -0.45,  0.5 ],
       [ 0.7 , -0.13, -1.78,  0.46]])

In [149]:
np.round(marr)  #rounding off values to zero decimal places

array([[-1.,  1.,  1., -0.],
       [-2., -0., -0.,  2.],
       [-1.,  0., -0.,  1.],
       [-0.,  2., -0.,  0.],
       [ 1., -0., -2.,  0.]])

In [151]:
#unique 
arr = np.array([1,1,2,3,4,2,3,4,1,3,8])

np.unique(arr)
# could also push in set......

array([1, 2, 3, 4, 8])